Jenkinsfile: default ccm branch/repo to master
since #2997 dtest CI is failing to run with following error:

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
```

since the dtest branch doesn't match like on release branch, we need
to be able to set it on the CI as needed, and also default it to work
with master