nodetool_additional_test: scrub_sstable_with_invalid_fragment: adjust expected errors
With recent changes in scylla, scrub no longer prints an error about
the invalid partition, cauding the scrub tests to fail.
For example, https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/234/artifact/logs-full.release.000/1682228954436_nodetool_additional_test.py%3A%3ATestNodetool%3A%3Atest_scrub_sstable_with_invalid_fragment/node1.log
```
INFO  2023-04-23 05:49:11,296 [shard 0] compaction - [Scrub ks.cf 923bd000-e19a-11ed-852d-fd71a6fa24b1] Scrubbing in skip mode [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-104koafq/test/node1/data/ks/cf-90c07aa0e19a11ed852dfd71a6fa24b1//me-2-big-Data.db:level=0:origin=reshard]
ERROR 2023-04-23 05:49:11,296 [shard 0] compaction - [Scrub compaction ks.cf] Invalid clustering row fragment with key 3 ({position: clustered, ckp{000400000003}, 0}) in partition ��� ({key: 000406000000, token:-5566252076597558760}), fragment is out-of-order compared to previous clustered fragment with key 5 ({position: clustered, ckp{000400000005}, 0})
ERROR 2023-04-23 05:49:11,296 [shard 0] compaction - [Scrub compaction ks.cf] Invalid clustering row fragment with key 3 ({position: clustered, ckp{000400000003}, 0}) in partition ���� ({key: 000400000000, token:-3485513579396041028}), fragment is out-of-order compared to previous clustered fragment with key 5 ({position: clustered, ckp{000400000005}, 0})
INFO  2023-04-23 05:49:11,301 [shard 0] compaction - [Scrub ks.cf 923bd000-e19a-11ed-852d-fd71a6fa24b1] Finished scrubbing in skip mode 1 sstables to [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-104koafq/test/node1/data/ks/cf-90c07aa0e19a11ed852dfd71a6fa24b1/me-4-big-Data.db:level=0]. 49kB to 49kB (~100% of original) in 4ms = 12MB/s. ~128 total partitions merged to 2.
```

https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/234/testReport/nodetool_additional_test/TestNodetool/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_scrub_sstable_with_invalid_fragment/
```
ccmlib.node.TimeoutError: 23 Apr 2023 05:49:11 [node1] Missing: ['\\[.* compaction ks.cf\\] Invalid partition']:
```

Allow either of the "Invalid (clustering row fragment|partition)"
errors.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>