compaction_additional_test: Wait for off-strategy to finish before check sstables
This patch is needed since #11848

Otherwise:

AssertionError: time window of 599 seconds is greater than 90.0
seconds margin:
sstable=/jenkins/workspace/releng/Scylla-CI/scylla/.dtest/dtest-_tm8cwob/test/node2/data/ks/test-bf0c05906edc11ed9b5ab93e6d4f1dcb/me-2-big-Statistics.db
min_timestamp=0 max_timestamp=599000000
assert 599 <= 90.0