offline_tools_test: test_sstableverify: improve error logging
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1175/testReport/offline_tools_test/TestOfflineTools/test_sstableverify/
just shows:
```
>       assert rc == 0, f"Invalid exit code: {str(rc)}"
E       AssertionError: Invalid exit code: 1
E       assert 1 == 0
E         +1
E         -0
```

But that's not enough to see the root cause, which is scylladb/scylla#10376:
```
    def assert_rc(rc, expected, out, error):
>       assert rc == expected, f"Invalid exit code: {str(rc)}\nstdout:\n{out}\nstderr:\n{error}"
E       AssertionError: Invalid exit code: 1
E         stdout:
E
E         stderr:
E         ERROR 09:57:24,685 Error in ThreadPoolExecutor
E         java.lang.RuntimeException: Unknown column storage during deserialization
E         	at org.apache.cassandra.db.SerializationHeader$Component.toHeader(SerializationHeader.java:338)
E         	at org.apache.cassandra.io.sstable.format.SSTableReader.open(SSTableReader.java:522)
E         	at org.apache.cassandra.io.sstable.format.SSTableReader.open(SSTableReader.java:385)
E         	at org.apache.cassandra.io.sstable.format.SSTableReader$3.run(SSTableReader.java:570)
E         	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
E         	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
E         	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
E         	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
E         	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:84)
E         	at java.base/java.lang.Thread.run(Thread.java:829)
E         Unknown keyspace/table keyspace1.standard1
E
E       assert 1 == 0
E         +1
E         -0
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>