sstableloader_test: rename set_test_data
since the method has `test` in its name, nosetests tries to run it
as any other test.

See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/695/testReport/sstableloader_test/AdditionalTestSSTableLoader/set_test_data/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
TypeError: set_test_data() missing 1 required positional argument: 'rows'
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>