nodetool_additional_test: scrub_with_one_node_expect_data_loss: update expected error message
Yet another way of scrub to report scrubbing errors
in abort mode.

Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/591/testReport/junit/nodetool_additional_test/TestNodetool/scrub_with_one_node_expect_data_loss_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/nodetool_additional_test.py", line 2072, in scrub_with_one_node_expect_data_loss_test
    self._scrub_with_one_node_expect_data_loss()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/nodetool_additional_test.py", line 2061, in _scrub_with_one_node_expect_data_loss
    node.watch_log_for("|".join(expected_errors), from_mark=mark, timeout=timeout)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/node.py", line 486, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 03 Oct 2021 22:26:02 [node1] Missing: ['Scrubbing .* failed|Finished scrubbing .* invalid|Compaction for ks/cf .*: scrub compaction failed']:
Scylla version 4.6.dev-0.20211003.adcd5a69d6 with .....
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/591/artifact/logs-all.debug.2/1633299965630_nodetool_additional_test.TestNodetool.scrub_with_one_node_expect_data_loss_test/node1.log:
```
INFO  2021-10-03 22:24:30,456 [shard 0] compaction_manager - compaction info: Compaction for ks/cf was stopped due to: scrub compaction found invalid data: stopping
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit 17dcb5336daf546cb5677faad2afa184965f2a29)