audit_tests: prepare datacenter
A bunch of audit tests to use NetworkTopologyStrategy
since `dc1` is never created.

For example, https://jenkins.scylladb.com/job/scylla-enterprise/job/dtest-release/446/testReport/audit_tests/CQLAuditTester/audit_keyspace_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-enterprise/dtest-release/scylla-dtest/audit_tests.py", line 206, in audit_keyspace_test
    self.verify_keyspace(audit_settings=AuditTester.audit_default_settings)
  File "/jenkins/workspace/scylla-enterprise/dtest-release/scylla-dtest/audit_tests.py", line 104, in verify_keyspace
    "ALTER KEYSPACE ks WITH replication = { 'class' : 'NetworkTopologyStrategy', 'dc1' : 1 } AND DURABLE_WRITES = false")
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.protocol.ConfigurationException: <Error from server: code=2300 [Query invalid because of configuration issue] message="Unrecognized strategy option {dc1} passed to org.apache.cassandra.locator.NetworkTopologyStrategy for keyspace ks">
```

Pass `nodes` as ` list to cluster.prepare
so it will put the node (a single one) in a datacenter
that is implicitly numbered as `dc1`.

While at it, decorate the audit tests with `@attr('single_node')`
since they all use a single-node cluster.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>