update_cluster_layout_tests: simple_add_two_nodes_in_parallel_test: fix flakiness
Currently the test waits on the "JOINING: sleeping 10000 ms for pending range setup"
on node2 before starting node3. But if node3 boots too quickly it might show up in
gossip before node2 bootstraps and then we don't see the expected message on node3:
"Checking bootstrapping/leaving/moving nodes: .* sleep 1 second and check again .*"
Occasionally leading to:
```
  Traceback (most recent call last):
    File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
      yield
    File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
      testMethod()
    File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/update_cluster_layout_tests.py", line 245, in simple_add_two_nodes_in_parallel_test
      self.assertTrue(False, "Node3 did not notice other node was booting")
    File "/usr/lib64/python3.7/unittest/case.py", line 722, in assertTrue
      raise self.failureException(msg)
  AssertionError: False is not true : Node3 did not notice other node was booting
```

This commit waits for "JOINING: Starting to bootstrap" instead on node2
since it happens after gossip determines the knownendpoints, e.g.:
```
  INFO  2020-03-26 12:57:43,663 [shard 0] gossip - Known endpoints=[127.0.44.1, 127.0.44.2], current_seeds={127.0.44.1}, seeds_from_config={127.0.44.1}, seen_any_seed=1
  INFO  2020-03-26 12:57:43,663 [shard 0] storage_service - JOINING: Starting to bootstrap...
```

Also, added a couple of debug messages and improved the pattern matching for the
"Checking bootstrapping" message to include node2's ip address.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>