pipelines: add one more possible string of spot termination
in some jobs we run into error we didn't yet identified as error
the indicates we got spot termination, and we need to retry

the error:

```
org.jenkinsci.plugins.workflow.support.steps.AgentOfflineException: Unable to create live FilePath for i-02384ebce9ea9fcee
```

Ref: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/749/consoleFull
(cherry picked from commit fffd8a80bfb775825e0021cad95550ed3bb9faa0)