compaction_additional_test: update regular expression to get sstable generations
This are currently specific to mc|md, and got broken now that
Scylla uses the "me" sstable format by default (since
scylladb/scylla@948bc359c23c86a97f34987017edc30143c03c74).

As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1123/testReport/junit/compaction_additional_test/TestCompactionAdditional/test_double_compaction_by_cleanup_and_major_compactions/
```
AssertionError: Compactions were not started. Expression: (Compacting|Cleaning) (.*\/ks\/cf.*\/(?:mc|md)-.*)
```

Extend the regular expression to m[c-e] and also prepare
for future formats that use the same naming convention: n[a-b]

Note that with this fix, test_double_compaction_by_cleanup_and_major_compactions
might still fail on #2394

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>