compaction_additional_test: count compactions for ks.cf
Currently the test counts any compactions on the node.
Apparently, that caused it to frequently fail in debug mode. See exmaple below.

This patch uses a filtering query to count only the compactions
of the user table we're interested in and base the test assumptions on that.

For example: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/481/testReport/compaction_additional_test/CompactionAdditionalTest/compaction_delete_with_smp_change_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/compaction_additional_test.py", line 111, in compaction_delete_with_smp_change_test
    self.assertGreater(numfound, 0)
  File "/usr/lib64/python3.7/unittest/case.py", line 1268, in assertGreater
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.7/unittest/case.py", line 710, in fail
    raise self.failureException(msg)
AssertionError: 0 not greater than 0
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>