heat_weighted_load_balancing_test: cut the samples tails to reduce flakiness
Previously, the test blindly examined sample (10,50) out of 60,
but that didn't work well due to different timing of scylla,
hence 050ca2dee34a02e568896fec68a841d5351341d9 looks for start/end
samples that make sense, but it still leaves samples at both edges
that are still too unstable for the test.

This change cuts the first 5 and last 5 samples to reduce
this flakiness.

Also, it prints more information about the failure in the `cached`
case.

For example, https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/823/testReport/heat_weighted_load_balancing_test/HeatWeightedLB/heat_weighted_load_balancing_cl_ONE_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/heat_weighted_load_balancing_test.py", line 223, in heat_weighted_load_balancing_cl_ONE_test
    self.run_heat_weighted_load_balancing('ONE')
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/heat_weighted_load_balancing_test.py", line 203, in run_heat_weighted_load_balancing
    self.verify_metrics(metrics)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/heat_weighted_load_balancing_test.py", line 83, in verify_metrics
    self.assertLessEqual(delta_ratio, 4)
  File "/usr/lib64/python3.7/unittest/case.py", line 1262, in assertLessEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.7/unittest/case.py", line 710, in fail
    raise self.failureException(msg)
AssertionError: 5.0127991096271565 not less than or equal to 4
```

Test: heat_weighted_load_balancing_test:HeatWeightedLB.heat_weighted_load_balancing_cl_ONE_test(release)
Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit d21f3eef5d3ba5ba5a1bb179ad19cc95c06e0454)