sstable_generation_loading_test: ignore sstableloader codec warnings
TestSSTableGenerationAndLoading tests fail occasionally with:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/sstable_generation_loading_test.py", line 204, in sstableloader_compression_deflate_to_snappy_test
    self.load_sstable_with_configuration('Deflate', 'Snappy')
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/sstable_generation_loading_test.py", line 291, in load_sstable_with_configuration
    self.assertEqual('', stderr, f"The stderr of sstableloader is not empty: {stderr}")
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 1250, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.7/unittest/case.py", line 710, in fail
    raise self.failureException(msg)
AssertionError: '' != 'WARN  03:00:51,340 Ignoring codec  [froze[179 chars]r]\n'
+ WARN  03:00:51,340 Ignoring codec  [frozen<tuple<int, uuid, bigint, bigint>> <-> java.nio.ByteBuffer] because it collides with previously registered codec  [frozen<tuple<int, uuid, bigint, bigint>> <-> java.nio.ByteBuffer]
 : The stderr of sstableloader is not empty: WARN  03:00:51,340 Ignoring codec  [frozen<tuple<int, uuid, bigint, bigint>> <-> java.nio.ByteBuffer] because it collides with previously registered codec  [frozen<tuple<int, uuid, bigint, bigint>> <-> java.nio.ByteBuffer]
```

See for example https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/896/testReport/sstable_generation_loading_test/TestSSTableGenerationAndLoading/

Although we don't exactly what causes this warning,
it is benign and the test shouldn't fail on it.

This change ignores this warning and just prints
a debug message when it is encountered.

Fixes #2120

DTest: sstable_generation_loading_test:TestSSTableGenerationAndLoading.{sstableloader_case_sensitive_with_quotes_test,sstableloader_compression_none_to_deflate_test,sstableloader_compression_none_to_snappy_test,sstableloader_compression_deflate_to_snappy_test} (dev)

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit c26a867ff9d2b372890719328ba9c0a666fb83f7)