compaction_additional_test: test_streaming_during_adding_node_with_boostrap: adjust shard_count for off-strategy compaction
Currently we wait only for the first shard to be done but
_sstable_count_is_close_to_time_windows_multiplied_by_shards_count
expects all shards to be done.

Failure seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/35/testReport/compaction_additional_test/TestTimeWindowDataSegregation/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split007___test_streaming_during_adding_node_with_boostrap/
```
>       assert expected_sstables_count + sstables_count_margin >= len(sstables) >= time_windows * shards_count, \
            f"Wrong sstables count on {node.name}. There should be at least one sstable per time window."
E       AssertionError: Wrong sstables count on node2. There should be at least one sstable per time window.
E       assert 20 >= (20 * 2)
E        +  where 20 = len(['/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-wyaputgv/test/node2/data/ks/test-a2140ad0f0...se/scylla/.dtest/dtest-wyaputgv/test/node2/data/ks/test-a2140ad0f05d11ecbd4ea6b0a281d5f0/me-35-big-Statistics.db', ...])
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/35/artifact/logs-full.release.007/1655704701564_compaction_additional_test.py%3A%3ATestTimeWindowDataSegregation%3A%3Atest_streaming_during_adding_node_with_boostrap/node2.log
doesn't show off-strategy / reshape compaction for ks.test on shard 0,
only on shard 1 until "initialization completed".

For the tested invariants, the number of sstables
and "Reshaped" messages should match the number of shards
that finished off-strategy compaction.

The test can't require all (or even any) shards to go through
off-strategy compaction.
The bottom line is that the sstable timestamps are validated
and the number of "Reshaped" messages matches the number
of "Done with off-strategy compaction" messages.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>