commitlog_test: test_total_space_limit_of_commitlog: allow off-by-one
To reduce flakiness, due to rounding, allow the commitlog size to
be 1 more than the current actual_space_limit.

As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/934/testReport/commitlog_test/TestCommitLog/test_total_space_limit_of_commitlog_with_small_limit/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/commitlog_test.py", line 915, in test_total_space_limit_of_commitlog_with_small_limit
    commitlog_total_space_in_mb=30)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/commitlog_test.py", line 865, in test_total_space_limit_of_commitlog
    'Out of total space limit')
  File "/usr/lib64/python3.7/unittest/case.py", line 1262, in assertLessEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.7/unittest/case.py", line 710, in fail
    raise self.failureException(msg)
AssertionError: 36 not less than or equal to 35 : Out of total space limit
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit 6c40756561b41c83c8bf9a26a50a5eec19b5b7f4)