compaction_additional_test: simulate_write_process_in_minutes: increase default num_pks
To prevent cases like https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/170/testReport/compaction_additional_test/TestTimeWindowDataSegregation/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split010___test_streaming_during_adding_node_with_boostrap/
```
AssertionError: Wrong sstables count on node2. There should be at least one sstable per time window.
assert 20 >= (20 * 2)
 +  where 20 = len(['/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-39zlxfpp/test/node2/data/ks/test-530511e08b...se/scylla/.dtest/dtest-39zlxfpp/test/node2/data/ks/test-530511e08b2711edaac32d212670b01b/me-32-big-Statistics.db', ...])
```

Looking at node2 log, with a small number of random pks which is
currently 10 by default, there is a small, 1/1024, chance that only
one of the shards will own the streamed data causing the test to fail
since it looks for num_windows * num_shards sstables.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>