wide_rows_test: shrink large partitions
No need to write a 60MB partitions over a 4MB threshold.
10MB would be just enough.  This will save some run time of the test.

Should also deflake test_large_partition_detector_with_node_stop
that tends to fail today in debug mode like
https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/170/testReport/wide_rows_test/TestWideRows_with_LeveledCompactionStrategy/test_large_partition_detector_with_node_stop/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/wide_rows_test.py", line 486, in test_large_partition_detector_with_node_stop
    expected_entity_data_size=expected_partition_data_size)
  File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/wide_rows_test.py", line 253, in validate_system_table
    entity_type=entity_type)
  File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/wide_rows_test.py", line 227, in validate_entity_size
    assert_equal_more_with_deviation(size, expected_size, row_size_threshold)
  File "/data/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/assertions.py", line 191, in assert_equal_more_with_deviation
    '%d' % (expect, deviation_high, actual)
AssertionError: Expect that result will be between 62400000 and 64272000, but received 51444166
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>