.github/workflows/add-label-when-promoted.yaml: do not nest ${{}} inside the condition
In https://github.com/scylladb/scylla-dtest/commit/2c14829b683825fe5433b7a9fc64f71e6ef05f5b we added a condition to run `Run auto-backport.py when promotion completed` only in `master` branch (and skip in releases)
That casued the following error:

```
python .github/scripts/auto-backport.py --repo scylladb/scylla-dtest --base-branch refs/heads/next --commits ..b2e594600ac73ecd5b78081441b3c9bf12c49baa
  shell: /usr/bin/bash -e {0}
  env:
    DEFAULT_BRANCH: master
    GITHUB_TOKEN: ***
Traceback (most recent call last):
  File "/home/runner/work/scylla-dtest/scylla-dtest/.github/scripts/auto-backport.py", line 162, in <module>
    main()
  File "/home/runner/work/scylla-dtest/scylla-dtest/.github/scripts/auto-backport.py", line 133, in main
    commits = repo.compare(start_commit, end_commit).commits
  File "/usr/lib/python3/dist-packages/github/Repository.py", line 888, in compare
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/commits/commits#compare-two-commits", "status": "404"}
```

Since this step failed because the github.event.before evaluates to an empty string. this is unexpected.

it is still recommended to use `${{}}` expression when the condition is a compound condition with one or more operators. this is what github's document is using in all its examples with compound condition.

So, in this change:
* use ${{}} expression when the condition is a compound condition to avoid this problem.
* do not use string interpolation in if condition.

Also, Since `GitHub.event.pull_request.state == 'closed'` is `true` for both `closed` and `merged` PRs and in dtest we always merge those PRs we can drop `github.event.pull_request.state == 'closed'` and leave only `github.event.pull_request.merged == true`

(cherry picked from commit 6c096b67d9763940f43c9eedcddb064dd671d7b6)