repair_additional_test: stop compaction before calling `sstable dump-data`
test could fail, with the following error:
```
subprocess.CalledProcessError: Command '['.../node2/bin/scylla', 'sstable', 'dump-data', '--merge',
'.../dtest-ozpnr_dn/test/node2/data/ks/cf-ce9676705c8f11eead2c022bf806306f/me-3g9p_1bs3_0hsfk2lnxmfzgwyxyn-big-Data.db',
'.../dtest-ozpnr_dn/test/node2/data/ks/cf-ce9676705c8f11eead2c022bf806306f/me-3g9p_1bsf_498z41z6a4iec2anmx-big-Data.db']'
returned non-zero exit status 1.
```

since we are not stopping compaction, so sstables it might get deleted
while running the command, so we stop the compaction