bootstrap_test: cluster_become_unavailable_when_kill_node_during_bootstrap: Explicitly pre-populate user data before bootstrap
In 00aeef0b5970c8dd7fc6ff68ed6dddee6a3f90eb we started waiting
for data to be written on node1 using `watch_log_for(compact_ks_msg)`
but unfortunately, in debug mode, we write so slowly that this doesn't
happen in time (10 minutes!), as seen in
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/261/testReport/bootstrap_test/TestBootstrap/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split015___test_cluster_become_unavailable_when_force_kill_node_during_bootstrap/
```
ccmlib.node.TimeoutError: 18 Oct 2023 05:56:56 [node1] Missing: ['Compact keyspace']:
```

While in release/dev modes this takes less than 10 seconds.

This patch runs stress for 30s before bootstrapping a new node
(while stress runs in the background, as before) to ensure there's
data on node1 before ndoe3's bootstrap.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>