nodetool_additional_test: scrub_with_one_node_expect_data_loss: fix expected message for sstable description
As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/929/testReport/nodetool_additional_test/TestNodetool/validate_with_one_node_expect_data_loss_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 2202, in validate_with_one_node_expect_data_loss_test
    self._scrub_with_one_node_expect_data_loss(mode="VALIDATE")
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 2062, in _scrub_with_one_node_expect_data_loss
    node.watch_log_for("|".join(expected_errors), from_mark=mark, timeout=timeout)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 486, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 14 Sep 2021 00:19:17 [node1] Missing: ['Scrubbing .* /jenkins/workspace/scylla\\-master/dtest\\-release/scylla/\\.dtest/dtest\\-1dcj028v/test/node1/data/ks/cf\\-4dbf018014f111eca1a2454a4e070839/md\\-5\\-big\\-Data\\.db failed|Finished scrubbing .* \\[/jenkins/workspace/scylla\\-master/dtest\\-release/scylla/\\.dtest/dtest\\-1dcj028v/test/node1/data/ks/cf\\-4dbf018014f111eca1a2454a4e070839/md\\-5\\-big\\-Data\\.db\\] - sstable(s) are invalid|Compaction for ks/cf .*: scrub compaction failed']:
```

The 'Finished scrubbing' message is there, but the sstable printout now
also carries its level and origin.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/929/artifact/logs-all.release.2/1631578760440_nodetool_additional_test.TestNodetool.validate_with_one_node_expect_data_loss_test/node1.log
```
INFO  2021-09-14 00:18:46,973 [shard 1] compaction - Finished scrubbing in validate mode [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-1dcj028v/test/node1/data/ks/cf-4dbf018014f111eca1a2454a4e070839/md-5-big-Data.db:level=0:origin=memtable] - sstable(s) are invalid
```

Generalize the expected message to also accomodate
for planned changes for making ABORT scrub mode use validate code.

DTest: {scrub,validate}_with_one_node_expect_data_loss_test

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit b21353627a9273efb98c23bca5acf1f96d5d9152)