migration_test: migrate_sstable_with_large_row_number_test: use get_sstables_files
Apprently, there could be leftover temporary sstable directories
after the node is stopped.  This is bad by itself but shouldn't fail this test.

Use scylla_tools.get_sstables_files() to retrieve the list of files to copy
and it is restricted to regular files (and may also filter out temporary
sstables, but that's not required in this test)

Error seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/486/testReport/sstableloader_test/TestMigration_with_3_0_x/migrate_sstable_with_large_row_number_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/migration_test.py", line 265, in migrate_sstable_with_large_row_number_test
    shutil.copy2(data_file, os.path.join(dir, os.path.basename(data_file)))
  File "/usr/lib64/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-yexsvejj/test/node1/data/keyspace1/standard1-ef00725098c311eab6b0000000000000/0000000000000021.sstable'
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>