nodetool_additional_test: filter audit keyspace
when `test_cfstats_syntax` is run with scylla-enterprise,
it was failing cause of extra keyspace `audit`

```
AssertionError: Expected ['ks1', 'ks2'] but got ['audit', 'ks1', 'ks2']
assert {'ks1', 'audit', 'ks2'} == {'ks1', 'ks2'}
  Extra items in the left set:
  'audit'
  Full diff:
  - {'ks1', 'ks2'}
  + {'ks1', 'audit', 'ks2'}
  ?         +++++++++
```