bootstrap_test: wait_other_notice when starting cluster
This is not the default when running with no test parallelism
(NODE_PROCESSES=1), like when running -a dtest-smoke.

and could lead to https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1547/testReport/junit/bootstrap_test/TestBootstrap/start_stop_test_node/
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/bootstrap_test.py", line 70, in start_stop_test_node
    node1.stop(wait_other_notice=True, wait_seconds=10)
  File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/scylla_node.py", line 706, in stop
    self.wait_until_stopped(wait_seconds, marks, dump_core=gently)
  File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/scylla_node.py", line 677, in wait_until_stopped
    node.watch_log_for_death(self, from_mark=mark)
  File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/node.py", line 469, in watch_log_for_death
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/node.py", line 443, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 27 Jan 2020 13:15:45 [node3] Missing: ['127.0.0.1 is now (dead|DOWN)']:

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>