cql_system_clients_test: purge anonymous conncections
`test_system_client_not_none_non_ssl` was failing from
time to time with the following error:

```
>       assert not empty_value_fields_map, f"expect fields Value with content, got {empty_value_fields_map}"
E       AssertionError: expect fields Value with content, got {'driver_name': None, 'driver_version': None}
E       assert not {'driver_name': None, 'driver_version': None}
```

and the first entry we get is really don't have the driver information:
```json
{'address': '127.0.0.1', 'port': 50011, 'client_type': 'cql', 'connection_stage': 'ESTABLISHED',
'driver_name': None, 'driver_version': None, 'hostname': None, 'protocol_version': 4, 'shard_id': 1,
'ssl_cipher_suite': None, 'ssl_enabled': None, 'ssl_protocol': None, 'username': 'anonymous'}
```

so we need to wait until `anonymous` users are being purged
before we do the validations