test_simple_add_two_nodes_in_parallel: node3 may not notice node2 in late_start case
If node3 starts too late it might not notice node2
and the test will falsely fail, as in
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/250/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split018___test_simple_add_two_nodes_in_parallel/
```
ccmlib.node.TimeoutError: 17 May 2023 04:04:15 [node3] Missing: ['Checking bootstrapping/leaving.* sleep 1 second and check again|Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while consistent_rangemovement is true|Node 127.0.32.2 has gossip status=UNKNOWN. Try fixing it before adding new node to the cluster']:
Scylla version 5.3.0~dev-0.20230517.9b0679c140bb
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>