nodetool_additional_test: stop using warmup in c-s
since from time to time we start seeing `test_concurrent_restart`
failing cause of unexpected failure output, such as:
```
java.lang.RuntimeException: Failed to execute warmup
```

which isn't part of failures mentioned in `stress_node_down_expected_errors`

since warmup are not relevent for scylla at all (and even in cassandra
they are for perf reasons only), i'm disabling warmups for the whole
test module, and not introducing it to `stress_node_down_expected_errors`