compaction_additional_test: test_streaming_{decommission,on_repair}: trigger and wait for offstrategy compaction
Those tests are currently flaky since they race
with offstrategy compaction that may not be triggered
before the test calls `_check_sstable_timestamps`.

For example: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/322/testReport/compaction_additional_test/TestTimeWindowDataSegregation/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split017___test_streaming_decommission/
```
AssertionError: time window of 1199 seconds is greater than 90.0                                    seconds margin: sstable=/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-di2zb1jy/test/node2/data/ks/test-05d5540030d811ee9007393178f2ffd7/me-3g86_05n9_2sb402ujuntri7kukb-big-Statistics.db                                    min_timestamp=0 max_timestamp=1199000000
assert 1199 <= 90.0
```

Or https://jenkins.scylladb.com/job/scylla-5.2/job/dtest-daily-release/27/testReport/compaction_additional_test/TestTimeWindowDataSegregation/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split016___test_streaming_decommission/
```
AssertionError: time window of 1199 seconds is greater than 90.0                                    seconds margin: sstable=/jenkins/workspace/scylla-5.2/dtest-daily-release/scylla/.dtest/dtest-gy5i3nor/test/node2/data/ks/test-43394f602ee211ee97cb5c5550e98f45/me-159-big-Statistics.db                                    min_timestamp=0 max_timestamp=1199000000
assert 1199 <= 90.0
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>