cql_tests: keyspace_test: populate required dcs
Since scylladb/scylla@b6fb5ee9128312f5d6a50c815ed5b147f757ccb9
the test would fail as seen in, e.g.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/399/testReport/junit/cql_tests/StorageProxyCQLTester/keyspace_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/cql_tests.py", line 85, in keyspace_test
    "ALTER KEYSPACE ks WITH replication = { 'class' : 'NetworkTopologyStrategy', 'dc1' : 1 } AND DURABLE_WRITES = false")
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.protocol.ConfigurationException: <Error from server: code=2300 [Query invalid because of configuration issue] message="Unrecognized strategy option {dc1} passed to org.apache.cassandra.locator.NetworkTopologyStrategy for keyspace ks">
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>