commitlog_test: fix assert boundary in compressed_segment_size_test
FAIL: default_compressed_segment_size_test (commitlog_test.TestCommitLog)
AssertionError: 33554432 not less than 33554432

FAIL: small_compressed_segment_size_test (commitlog_test.TestCommitLog)
AssertionError: 5242880 not less than 5242880

Re-enable those two subtests after fixed the boundary problem.

Signed-off-by: Amos Kong <amos@scylladb.com>
(cherry picked from commit b71e113f706c3de808efa1b43655825622bdd98f)