ttl_tests: allow 1 second uncertainty window
Recently we've hit 2 failures realted to ttl accuracy.

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/891/testReport/junit/ttl_test/TestTTL/insert_ttl_has_priority_on_defaut_ttl_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/ttl_test.py", line 131, in insert_ttl_has_priority_on_defaut_ttl_test
    [[1, 1, 1, 1]])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1661, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 99, in assert_all
    assert list_res == expected, error
AssertionError: Expected [[1, 1, 1, 1]] from SELECT * FROM ttl_table;, but got []
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/895/testReport/ttl_test/TestTTL/insert_ttl_works_without_default_ttl_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/ttl_test.py", line 154, in insert_ttl_works_without_default_ttl_test
    assert_all(self.session1, "SELECT * FROM ttl_table;", [[1, 1, 1, 1]])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1661, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 99, in assert_all
    assert list_res == expected, error
AssertionError: Expected [[1, 1, 1, 1]] from SELECT * FROM ttl_table;, but got []
```

Since the TTL logic adds a TTL in whole seconds
to a timestamp, also in whole second resolution
the test cannot know exactly when data is going to expire.

We can only assert that the data must not expire too
early, that is less than ttl-1 seconds from the
earliest time the query had been processed (rounded
down), and it must expire within ttl+1 seconds from
the latest query timestamp.

DTest: ttl_test:TestTTL.{insert_ttl_has_priority_on_defaut_ttl_test,insert_ttl_works_without_default_ttl_test (dev)

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>