compaction_additional_test: trigger offstrategy compaction after rebuild
With https://github.com/scylladb/scylladb/pull/11848 offstrategy
compaction is enabled by default after all streaming-based node
operations.  However, it is triggered only after a timeout of
5 minutes.  This causes test_rebuild_node_streaming to fail
as in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/169/testReport/compaction_additional_test/TestTimeWindowDataSegregation/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split017___test_rebuild_node_streaming/
```
AssertionError: time window of 599 seconds is greater than 90.0                                    seconds margin: sstable=/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-mcfw8p5w/test/node3/data/ks/test-5a991e508a7e11edaee95652e7afaa32/me-3-big-Statistics.db                                    min_timestamp=0 max_timestamp=599000000
assert 599 <= 90.0
```

Trigger offstrategy compaction manuall after rebuild is done
to make sure the streamed sstables are reshaped into the compaction
strategy invariant.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>