cql_cast_test: test for 3111: change require decoration to skip
Although scylladb/scylla#3111 was closed, cast_issue_3111_test
fails exactly cast_issue_3109_test:
```
Traceback (most recent call last):
  File "/home/bhalevy/dev/scylla-dtest/cql_cast_test.py", line 148, in cast_issue_3111_test
    test_types=['cast', 'sum', 'min', 'max', 'min', 'max', 'avg'], exclude=False)
  File "/home/bhalevy/dev/scylla-dtest/cql_cast_test.py", line 225, in _test_run
    test_types=test_types, test_to=test_to, compare_error=compare_error)
  File "/home/bhalevy/dev/scylla-dtest/cql_cast_test.py", line 271, in _test_one_type
    from_type, to_type, exp_result, actual_result))
AssertionError: '-564' != '-564.0'
- -564
+ -564.0
?     ++
 : casting from type float to type decimal: expected -564.0 but got -564
```

As per the decision in https://github.com/scylladb/scylla/issues/3109#issuecomment-410516282
this isn't going to change any time soon so skip the test
unconditionally.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>