cqlsh_copy_test: test_bulk_round_trip_with_timeouts: adjust to debug mode
To deal with timeout in debug mode, as seen in the following run.

The problem is that the configured timeouts are too short for debug mode
so we make zero progress.

This change asjusts the test to debug mode by:
- decreasing the number of operations so the test runs in a reasonable
  time
- increase the requests timeouts so we can make forward progress.

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-parallel/130/testReport/cqlsh_tests.cqlsh_copy_tests/CqlshCopyTest/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split002___test_bulk_round_trip_with_timeouts/
```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/nose/plugins/multiprocess.py", line 812, in run
        test(orig)
      File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 46, in __call__
        return self.run(*arg, **kwarg)
      File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 134, in run
        self.runTest(result)
      File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 152, in runTest
        test(result)
      File "/usr/lib64/python3.7/unittest/case.py", line 693, in __call__
        return self.run(*args, **kwds)
      File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
        testMethod()
      File "/jenkins/workspace/scylla-master/dtest-debug-parallel/scylla-dtest/cqlsh_tests/cqlsh_copy_tests.py", line 1382, in test_bulk_round_trip_with_timeouts
        copy_from_success=copy_from_success)
      File "/jenkins/workspace/scylla-master/dtest-debug-parallel/scylla-dtest/cqlsh_tests/cqlsh_copy_tests.py", line 1307, in _test_bulk_round_trip
        run_copy_to(tempfile1)
      File "/jenkins/workspace/scylla-master/dtest-debug-parallel/scylla-dtest/cqlsh_tests/cqlsh_copy_tests.py", line 1284, in run_copy_to
        result = self.node1.run_cqlsh(cmds=copy_to_cmd)
      File "/jenkins/workspace/scylla-master/dtest-debug-parallel/scylla-ccm/ccmlib/node.py", line 869, in run_cqlsh
        output = p.communicate()
      File "/usr/lib64/python3.7/subprocess.py", line 975, in communicate
        self._wait(timeout=sigint_timeout)
      File "/usr/lib64/python3.7/subprocess.py", line 1647, in _wait
        time.sleep(delay)
      File "/usr/local/lib/python3.7/site-packages/nose/plugins/multiprocess.py", line 276, in signalhandler
        raise TimedOutException()
    nose.plugins.multiprocess.TimedOutException: 'test_bulk_round_trip_with_timeouts (cqlsh_tests.cqlsh_copy_tests.CqlshCopyTest)'
```

Dtest: cqlsh_tests/cqlsh_copy_tests.py:CqlshCopyTest.test_bulk_round_trip_with_timeouts(debug)

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit a1864b5ac341a0fdac33af5ce60c0b930fb17a19)