materialized_views_test: _mv_populating_from_existing_data_during_changes_test: remove exception handling
Commit 7249ce349cd1881c2d1900ca60e3d7617b75cdb2 removed
the `fail` parameter so we now see this:
  Traceback (most recent call last):
    File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
      yield
    File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
      testMethod()
    File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 597, in mv_populating_from_existing_data_during_extend_test
      self._mv_populating_from_existing_data_during_changes_test('add node', nodes=4, rf=3, mvs=10, prefill=40000)
    File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 677, in _mv_populating_from_existing_data_during_changes_test
      if not fail:
  NameError: name 'fail' is not defined

However, `fail` was always passed as `False` so there is
no need to catch the exception.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>