hintedhandoff_additional_test.py: Remove removenode_test from gating
The removenode_test() fails as follows during next promotion:

  ======================================================================
  ERROR: hintedhandoff_removenode_test (hintedhandoff_additional_test.TestHintedHandoff)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/jenkins/workspace/scylla-master/next/scylla-dtest/hintedhandoff_additional_test.py", line 136, in hintedhandoff_removenode_test
      node.watch_log_for(msgs, from_mark=from_mark, timeout=node_timeout)
    File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/node.py", line 443, in watch_log_for
      [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
  TimeoutError: 18 Dec 2019 16:44:56 [node2] Missing: ['hints_manager - drain_for: finished draining 127.0.86.3']:
  INFO  2019-12-18 16:44:23,643 [shard 0] rpc - clie.....
  See system.log for remainder

The test was updated recently, but it's not clear if this is scylla
regression or test problem. Let's drop the test from next-gating for now
to avoid blocking next.