heat_weighted_load_balancing_test: further deflake verify_metrics
We still see occasional failures of heat_weighted_load_balancing tests
where the delta ratio after restart is lower than the present lower
bound.  This indicates that the cache on the restarted node is heating
slightly faster than expected which is actually a good thing.

There is no need to fail the test in this case so relax the lower
bound to start at 1.1 down to 0.9 (based on manual inspection
of the values closer to the test end (in the 50-60 out of 60 samples
range).

Recent failures of heat_weighted_load_balancing_cl_QUORUM_test
for exameple show:
```
AssertionError: Cache difference between node1 and node2 is out of range: 19901.2/15944.2=1.2481780208477065 expected to be 1.35 < ratio <= 11.35. index=43 metric scylla_storage_proxy_coordinator_reads_local_node
AssertionError: Cache difference between node1 and node2 is out of range: 18309.4/15287.6=1.1976634658154321 expected to be 1.3 < ratio <= 11.3. index=44 metric scylla_storage_proxy_coordinator_reads_local_node
AssertionError: Cache difference between node1 and node2 is out of range: 20605.6/15477.8=1.3313003139981134 expected to be 1.4 < ratio <= 11.4. index=42 metric scylla_storage_proxy_coordinator_reads_local_node
AssertionError: Cache difference between node1 and node2 is out of range: 19365.6/13565.6=1.4275520434039037 expected to be 1.45 < ratio <= 11.45. index=41 metric scylla_storage_proxy_coordinator_reads_local_node
AssertionError: Cache difference between node1 and node2 is out of range: 22555.2/16298.0=1.3839244079028101 expected to be 1.5 < ratio <= 11.5. index=40 metric scylla_storage_proxy_coordinator_reads_local_node
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit 0e21cd643aba824bef65f55afa2b2484c3775d52)