doc: fix pip install command for ccm
Add missing #egg=ccm

    ERROR: Could not detect requirement name for
           'git+https://github.com/scylladb/scylla-ccm.git',
           please specify one with #egg=your_package_name

Signed-off-by: Alejo Sanchez <alejo.sanchez@scylladb.com>