test_add_node_with_large_partition4: use explicit cql queries to populate data
Using cassandra-stress to populate the data is unnecessary
and cause flakiness as seen both in release modem but
in particular with debug mode.

For example, https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/261/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_add_node_with_large_partition4/
```
>       self.check_rows_on_node(node2, nr_rows, ks='keyspace1', cf='standard1', timeout=timeout)

update_cluster_layout_tests.py:1812:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <update_cluster_layout_tests.TestUpdateClusterLayout object at 0x7ff0229813d0>
node_to_check = <ccmlib.scylla_node.ScyllaNode object at 0x7ff0203c9f50>
rows = 30000, found = [], missings = [], restart = True, ks = 'keyspace1'
cf = 'standard1', timeout = 900

    def check_rows_on_node(self, node_to_check, rows, found=None, missings=None, restart=True, ks='ks', cf='cf',
                           timeout=None):
        if found is None:
            found = []
        if missings is None:
            missings = []
        stopped_nodes = []

        for node in self.cluster.nodes.values():
            if node.is_running() and node is not node_to_check:
                stopped_nodes.append(node)
                node.stop(wait_other_notice=True)

        if not timeout:
            timeout = self.cql_timeout(300)

        session = self.patient_cql_connection(node_to_check, ks)
        query = SimpleStatement(f"SELECT * FROM {ks}.{cf} LIMIT {rows * 2}",
                                consistency_level=ConsistencyLevel.ONE)
        result = session.execute(query, timeout=timeout)
        if rows > 1000:
            # count the number by iterating the resultset for smaller memory footprint
            count = sum(1 for _ in result)
        else:
            count = len(list(result))
>       assert count == rows
E       assert 24000 == 30000
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>