nodetool_additional_test: scrub_with_one_node_expect_data_loss: fix log parsing
Currently the expected errors are focused only
on the case where scrub reports a failure.
that may lead to a watch_log_for timeout when scrub succeeds
scrubbing the sstable we inject random corruption into.

As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1163/testReport/nodetool_additional_test/TestNodetool/test_scrub_with_one_node_expect_data_loss/
```
ccmlib.node.TimeoutError: 28 Mar 2022 10:57:18 [node1] Missing: ['Scrubbing .* failed|Finished scrubbing .*/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-pjm01zft/test/node1/data/ks/cf-be80fad0ae8511ecb83f0c412c64841a/me-3-big-Data.db|Compaction for ks/cf .*: scrub compaction (failed|found invalid data)']:
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1163/artifact/logs-all.release.2/1648465041539_nodetool_additional_test.py%3A%3ATestNodetool%3A%3Atest_scrub_with_one_node_expect_data_loss/node1.log
```
INFO  2022-03-28 10:56:47,922 [shard 1] compaction - [Scrub ks.cf c3b93120-ae85-11ec-bfc3-5322e6687700] Scrubbing in abort mode [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-pjm01zft/test/node1/data/ks/cf-be80fad0ae8511ecb83f0c412c64841a/me-3-big-Data.db:level=0:origin=memtable]
WARN  2022-03-28 10:56:47,925 [shard 1] mc_writer - Capping tombstone local_deletion_time 2147483647 to max 2147483646
INFO  2022-03-28 10:56:47,929 [shard 1] compaction - [Scrub ks.cf c3b93120-ae85-11ec-bfc3-5322e6687700] Finished scrubbing in abort mode 1 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-pjm01zft/test/node1/data/ks/cf-be80fad0ae8511ecb83f0c412c64841a/me-7-big-Data.db:level=0]. 258kB to 167kB (~65% of original) in 6ms = 27MB/s. ~2560 total partitions merged to 1551.
```

This change splits log parsing into 2 parts:
First, detect the scrub job start message, based on the known sstable name.
Then wait for the finish message.
In both cases, expect to see "failed" or "invalid" in the log line,
otherwise, retry with another sstable.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>