pipelines: fix customFailurePatterns regex
seems like recent addition of `agent-offline` regex

can cause the following error:

```
Error: dtest phase failed, going ahead to check tests and dtest status, error:
|java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 774
```

which in turn stop retries for  working

it's basiclly was a typo, and we have `*` before `.` and not the other way around

(cherry picked from commit c637df4d2d1818d8699e1b8f8ebef45e4f5df1f8)