compaction_additional_test: refresh_and_restart_after_compaction_strategy_change_test: set min_threshold to 2
Although setting min_threshold and/or max_throshold to 1
is currently allowed by scylla, they do not make sense
as they don't ensure forward progress and setting min_threshold=1
for TWCS is currently messing up its reshaping logic.

This causes the test to fail since
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1017/testReport/junit/compaction_additional_test/CompactionAdditionalTest/refresh_and_restart_after_compaction_strategy_change_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/compaction_additional_test.py", line 577, in refresh_and_restart_after_compaction_strategy_change_test
    self.assertEqual(len(subtests_errs), 0, 'Exception occured in subtest')
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 4 != 0 : Exception occured in subtest
```

where no reshaping compaction happens.

This change set min_threshold=2 and does not specify
max_threshold as it seems irrelevant to the test.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>