test_repair_streams_data_from_closest_node: use regex for splitting peers list
b2892932b6557be446a42ef64f14bcd4375b7f47 adjusted the test for tablets,
however, there's still a bug in the way the list of peer addresses
is prepared, where the matching string is split by separating commas,
while leaves space characters in the resulting address strings,
screwing up the matching algorithm.

This can be seen in e.g.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/tablets/job/dtest-release-with-tablets/10/testReport/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_repair_streams_data_from_closest_node/
```
AssertionError: New node should fetch data from the same dc
assert '127.0.2.3' in ['127.0.2.2', ' 127.0.2.3', ' 127.0.2.1']
```

Rather than calling strip() after split()
just simplify the function by using a regular expression
for a delimiter that allows optional space characters surrounding a comma.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit af6dea3e1aa32d855e7c1f03365f3fbebcb9e532)