nodetool_additional_test: validation_expected_errs: add "compaction found invalid data"
This is error can be printed in the log by scrub compaction.
For example:
```
FAIL: scrub_with_multi_nodes_expect_data_rebuild_test (nodetool_additional_test.TestNodetool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bhalevy/dev/scylla-dtest/dtest.py", line 1148, in tearDown
    self.cleanUpCluster()
  File "/home/bhalevy/dev/scylla-dtest/dtest.py", line 1202, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
AssertionError: Unexpected errors found: [('node1', ['ERROR 2021-10-31 15:23:57,678 [shard 0] compaction_manager - compaction info: Compaction for ks/cf was aborted due to: scrub compaction found invalid data: stopping'])]
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit a9e6c9f7393a2ea77f19f6181e7df88b5d5d6fb2)