rest_api_tests: test_basic_rest_uptime: improve allowed ranges
Both the test clock and scylla clock have much better
resolution than 1 second so the upper limit of 11 seconds
is bogus.

As for the lower limit, we can undershoot as well
as seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/188/testReport/rest_api_tests/TestScyllaARestApi/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_basic_rest_uptime/
```
AssertionError: The uptime received from scylla does not match the expected uptime
assert 10000 <= (11122 - 1123)
```

so fix the limits to allow a margin of 10 milliseconds
around the sleep time of 10 seconds.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>