secondary_indexes_test: _node_action_during_index_build: add expected error
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/313/testReport/secondary_indexes_test/TestSecondaryIndexes/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split014___test_stop_node_during_index_build/
```
AssertionError: ERROR 2023-07-25 02:20:14,249 [shard 1] view - Error applying view update to 127.0.95.2 (view: ks.b_index_index, base token: 5867634871768655372, view token: 1590958621126160411): exceptions::mutation_write_failure_exception (abort requested)
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>