resharding_test: _resharding_basic: disable compaction
Regular compaction duringthe test can interfere
with _verify_number_of_data_files, as seen in
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/247/testReport/resharding_test/TestReshardingSingleNodeGating/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split028___test_resharding_by_murmur3_gating_1_TimeWindowCompactionStrategy_15_/
```
self = <resharding_test.TestReshardingSingleNodeGating object at 0x7f03fbecf810>
node_count = 1, compaction_strategy = 'TimeWindowCompactionStrategy'
murmur3 = 15

    def test_resharding_by_murmur3_gating(self, node_count, compaction_strategy, murmur3):
        """
        Cluster with 10M objects. Both SMP and MURMUR3 parameter are changed
        and restarting the cluster
        """
>       self._resharding_basic(self.SMP_FOR_INCREASE, rows=1000, murmur3=self.MURMUR3_PARTITIONER_FOR_INCREASE)

resharding_test.py:210:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
resharding_test.py:181: in _resharding_basic
    self._verify_number_of_data_files(data_files_num_before=data_files_num_before, reshard_to=reshard_to,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <resharding_test.TestReshardingSingleNodeGating object at 0x7f03fbecf810>
data_files_num_before = 5, reshard_to = 6, actual_data_files_num = 32
ks = 'keyspace1', cf = 'standard1'

    def _verify_number_of_data_files(self, data_files_num_before, reshard_to, actual_data_files_num=None,
                                     ks='keyspace1', cf='standard1'):
        logger.debug('Verify number of data files')
        expected_num = data_files_num_before * reshard_to
        if not actual_data_files_num:
            actual_data_files_num = self._get_number_of_data_files(ks, cf)
>       assert actual_data_files_num <= expected_num, \
            f'{actual_data_files_num} not less than or equal to {expected_num}. Data files amount ' \
            f'after resharding should be not more then data files amount before ' \
            f'resharding multiplying by {reshard_to}.'
E       AssertionError: 32 not less than or equal to 30. Data files amount after resharding should be not more then data files amount before resharding multiplying by 6.
E       assert 32 <= 30

resharding_test.py:87: AssertionError
```

This change disables regular compaction using the `enabled=false`
compaction option when creating the stress table.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>