nodetool_additional_test: nodetool_refresh_with_data_perms_test: filter Permission denied errors
scylladb/seastar@7527881ff may report a Permission denied error
when calling `perf_event_open` in `cpu_stall_detector_linux_perf_event`
and this breaks nodetool_refresh_with_data_perms_test that looks for
any "Permission denied" error whatsoever.

This caused a regression since https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/938/testReport/junit/nodetool_additional_test/TestNodetool/nodetool_refresh_with_data_perms_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1410, in nodetool_refresh_with_data_perms_test
    self.assertFalse(len(errors), 'Permission denied errors found')
  File "/usr/lib64/python3.7/unittest/case.py", line 716, in assertFalse
    raise self.failureException(msg)
AssertionError: 2 is not false : Permission denied errors found
```

Filter the found log errors out of the `perf_event` related ones.

Also, make this a single_node test to speed it up.
There's no need for a 2-node cluster for this test.

While at it, also fix a typo in assertion error message
after `node.nodetool("enablegossip", True)`

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit 824cbcca58dcef810865710e82aaa37c2577c150)