compaction_test: test_delete_tombstone_gc_node_down: trigger and wait for offstrategy compaction after all repairs
Currently the test waits for offstrategy compaction only
after repairing the restarted node4, however, tombstones
may be added later on when running repair on other nodes,
and those will cause the test to fail as in
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/119/testReport/compaction_test/TestCompaction/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split048___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_/
```
>           self.verify_deleted(session=session, node=node4, num_deleted_rows=0)

compaction_test.py:345:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <compaction_test.TestCompaction object at 0x7f48391d3190>
session = <cassandra.cluster.Session object at 0x7f48392db5e0>
node = <ccmlib.scylla_node.ScyllaNode object at 0x7f48398288b0>
num_deleted_rows = 0

    def verify_deleted(self, session, node, num_deleted_rows):
        """
            This method verifies there are <num_deleted_rows> deleted rows (tombstones) on node.
        """
        count, jsoninfo = self.count_deleted(session=session, node=node)
>       assert count == num_deleted_rows, "Error: expected {} deleted partitions but found {}:\n{}".format(
            0, count, len(jsoninfo))
E       AssertionError: Error: expected 0 deleted partitions but found 1:
E         1513363
E       assert 1 == 0
E         +1
E         -0
```

Instead, trigger and wait for offstrategy compaction to be done
after running repair on all nodes, and only then verify there are
no deleted rows.

Ref scylladb/scylladb#12383

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>