cql_additional_tests: keyspace_creation_options_test: populate required dcs
Since scylladb/scylla@b6fb5ee9128312f5d6a50c815ed5b147f757ccb9
the test would fail as seen in, e.g. https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/dtest-release/197/testReport/cql_additional_tests/TestCQL/keyspace_creation_options_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/releng-testing/dtest-release/scylla-dtest/cql_additional_tests.py", line 1926, in keyspace_creation_options_test
    """)
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.protocol.ConfigurationException: <Error from server: code=2300 [Query invalid because of configuration issue] message="Unrecognized strategy option {us-east} passed to org.apache.cassandra.locator.NetworkTopologyStrategy for keyspace foo">
```

This change populates the requires datacenters so that they would be
find by scylla when validating the NetworkTopologyStrategy options.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>