compaction_additional_test: clearer run_sstablemetadata failure
the failure message was:
```
>   min_timestamp = min([int(min_compile.search(r[0]).group(1)) for r in res])
E   AttributeError: 'NoneType' object has no attribute 'group'
```

and now it's:
```
>           pytest.fail(f'\nsstablemetadata failed with the following:\n\n{"".join(errors)}')
E           Failed:
E           sstablemetadata failed with the following:
E
E           WARN  16:55:10,807 Only 34.172GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
E           Exception in thread "main" java.security.InvalidParameterException: SSTable Format: 'me' is unsupported.
E           	at org.apache.cassandra.tools.SSTableMetadataViewer$SSTableFormat.fromString(SSTableMetadataViewer.java:85)
E           	at org.apache.cassandra.tools.SSTableMetadataViewer.main(SSTableMetadataViewer.java:166)
```

this is not fixing the root cause of the issue, which is
in scylla-tools: https://github.com/scylladb/scylla-tools-java/issues/291