repair_additional_test: require scylladb/scylla#9785 from flaky next_gating tests
These tests are flaky due to scylladb/scylla#9785
and fail frequently in next promotion.

E.g. https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4370/testReport/junit/repair_additional_test/TestRepairAdditional/dtest___test_repair_one_missing_row/
```
    def check_repair_tx_rx_rows(self, node_to_check, expected_tx_row_nr, expected_rx_row_nr):
        tx = 0
        rx = 0
        for line in node_to_check.grep_log("stats: repair_reason=repair"):
            line = line[0]
            logger.debug(line)
            kv = re.findall(r"tx_row_nr=\d*", line)[0].split('=')
            logger.debug(kv)
            tx += int(kv[1])
            kv = re.findall(r"rx_row_nr=\d*", line)[0].split('=')
            logger.debug(kv)
            rx += int(kv[1])
        assert tx == expected_tx_row_nr
>       assert rx == expected_rx_row_nr
E       assert 0 == 1
E         +0
E         -1
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4362/testReport/repair_additional_test/TestRepairAdditional/dtest___test_repair_joint_row_3nodes_2/
```
    def check_repair_tx_rx_rows(self, node_to_check, expected_tx_row_nr, expected_rx_row_nr):
        tx = 0
        rx = 0
        for line in node_to_check.grep_log("stats: repair_reason=repair"):
            line = line[0]
            logger.debug(line)
            kv = re.findall(r"tx_row_nr=\d*", line)[0].split('=')
            logger.debug(kv)
            tx += int(kv[1])
            kv = re.findall(r"rx_row_nr=\d*", line)[0].split('=')
            logger.debug(kv)
            rx += int(kv[1])
>       assert tx == expected_tx_row_nr
E       assert 0 == 40
E         +0
E         -40
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>