update_cluster_layout_tests: _simple_add_new_node_while_schema_changes: fix stray comma in message
The expected log message that was added in #1788
has a stray comma at the end.

See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/687/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/simple_add_new_node_while_schema_changes_with_repair_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/update_cluster_layout_tests.py", line 671, in simple_add_new_node_while_schema_changes_with_repair_test
    self._simple_add_new_node_while_schema_changes(enable_repair_based_node_ops=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/update_cluster_layout_tests.py", line 654, in _simple_add_new_node_while_schema_changes
    node4.watch_log_for("completed successfully, keyspace=ks,")
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 449, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 10 Dec 2020 10:42:52 [node4] Missing: ['completed successfully, keyspace=ks,']:
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>