hintedhandoff_additional_test: hintedhandoff_dont_revive_test: fix call to __jvm_args
Node parameter removed in 08d51171f40f6be98d8faa2906e48afb69c3d8fd
but this call site was overlooked unintentionally.

Caused following failure in
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/647/testReport/hintedhandoff_additional_test/TestHintedHandoff/hintedhandoff_dont_revive_test/:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/hintedhandoff_additional_test.py", line 398, in hintedhandoff_dont_revive_test
    hinting_node.start(wait_for_binary_proto=True, jvm_args=self.__jvm_args(hinting_node))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 427, in start
    if '=' in jvm_arg:
TypeError: argument of type 'ScyllaNode' is not iterable
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>