bypass_cache_test: test both cache_index_pages configs
As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/149/testReport/bypass_cache_test/TestBypassCache/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_create_table_caching_disabled/ and friends:

```
AssertionError: Running query that is suppose to read from disk following errors found:
  Metric scylla_sstables_index_page_hits changed by less than 800, before:0, after:0
  Metric scylla_sstables_index_page_cache_misses should be increased by 1, before:0, after:0
  Metric scylla_sstables_index_page_cache_populations should be increased by 1, before:0, after:0
assert not ['Metric scylla_sstables_index_page_hits changed by less than 800, before:0, after:0', 'Metric scylla_sstables_index_p... before:0, after:0', 'Metric scylla_sstables_index_page_cache_populations should be increased by 1, before:0, after:0']
```

The test is unaware of scylladb/scylladb@a75e4e1.
This change parameterizes the respective test cases for both cases.

Fixes #2927

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>