compaction_delete_with_smp_change_test: count compactions before delete
As seen when testing scylla in debug mode, the test might miss
compaction that happen after deleting the data and before getting
the basic compactions_1 = compactions_count(), leading
to failure like the following:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/lastFailedBuild/testReport/junit/compaction_additional_test/CompactionAdditionalTest/compaction_delete_with_smp_change_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/compaction_additional_test.py", line 116, in compaction_delete_with_smp_change_test
    self.assertGreater(numfound, 0)
  File "/usr/lib64/python3.7/unittest/case.py", line 1268, in assertGreater
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.7/unittest/case.py", line 710, in fail
    raise self.failureException(msg)
AssertionError: 0 not greater than 0
```

To fix that, get the basic compaction count right after deleting the keys
and flushing the memtable so the delta will include any compactions that
happened after that.

Test: compaction_additional_test.py:CompactionAdditionalTest.compaction_delete_with_smp_change_test(dev, debug)

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>