secondary_indexes_test: update Error applying view update ignore pattern
The message format was changed in
scylladb/scylla@793665232200c602fd9df4a8f26febc762aae713
causing secondary_index tests to fail as follows:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/797/testReport/secondary_indexes_test/TestSecondaryIndexes/test_stop_node_during_index_build/
Scylla version scylladb/scylla@f7f5fca5a855869398eec8878bbce88c7d1132ac
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 1327, in test_stop_node_during_index_build
    self._node_action_during_index_build(node_action='stop', nodes=4, rf=3, num_rows=100000)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 1408, in _node_action_during_index_build
    self.check_errors(self.cluster.nodelist()[0], exclude_errors=exclude_errors, regex=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1299, in check_errors
    assert False, '\n'.join(list(errors))
AssertionError: ERROR 2021-04-26 02:06:41,210 [shard 0] view - Error applying view update to 127.0.11.2 (view: ks.b_index_index, base token: 7234171581732002168, view token: 6892678355634339412): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2021-04-26 02:06:43,211 [shard 0] view - Error applying view update to 127.0.11.2 (view: ks.b_index_index, base token: 7234171581732002168, view token: 6892678355634339412): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2021-04-26 02:06:40,209 [shard 0] view - Error applying view update to 127.0.11.2 (view: ks.b_index_index, base token: 7234171581732002168, view token: 6892678355634339412): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
```

This change add a wildcard after the stopped node address
as already used elsewhere wrt this error message.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit 1fe1ce3abf104f512fed92784999ac246e44fcc4)