test_simple_add_two_nodes_in_parallel: wait for gossip message in early start case
As seen in https://jenkins.scylladb.com/job/scylla-5.1/job/dtest-daily-release/71/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split017___test_simple_add_two_nodes_in_parallel_case_0_/
```
ccmlib.node.TimeoutError: 30 Jul 2023 15:48:22 [node3] Missing: ['Checking bootstrapping/leaving.* sleep 1 second and check again|Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while consistent_rangemovement is true|Node 127.0.7.2 has gossip status=UNKNOWN. Try fixing it before adding new node to the cluster']:
```

https://jenkins.scylladb.com/job/scylla-5.1/job/dtest-daily-release/71/artifact/logs-full.release.017/1690732105372_update_cluster_layout_tests.py%3A%3ATestUpdateClusterLayout%3A%3Atest_simple_add_two_nodes_in_parallel%5Bcase_0%5D/node3.log
```
INFO  2023-07-30 15:38:31,495 [shard 0] storage_service - Checking bootstrapping/leaving nodes: ok
```

node3 started too early so it didn't see node2 as bootstrapping.
Unfortunately, this can still happen with gossip-based topology changes.

Deflake the test by waiting for another message from gossiper after which
node3 is supposed to see node as bootstrapping (in an UNKNOWN state).

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>