dtest: Tester: initialize setUp members on __init__
To prevent failure to find these attributes when tearDown is called
before setUp.

For example:
  Traceback (most recent call last):
    File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/cql_additional_tests.py", line 5062, in mc_migrate_scylla_to_cassandra
      cc.tearDown()
    File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/scylla_tools.py", line 1154, in tearDown
      self.tester.tearDown()
    File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/dtest.py", line 895, in tearDown
      for runner in self.runners:
  AttributeError: 'Tester' object has no attribute 'runners'
  mc_sstables_case_sensitive_add_column_test (cql_additional_tests.TestCQL) ... ERROR

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>