resharding_test: get_number_of_data_files: don't count temporary sstables
resharding_by_murmur3_gating_test fails from time to time like this:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-4.1/next/scylla-dtest/resharding_test.py", line 185, in resharding_by_murmur3_gating_test
    self._resharding_basic(self.SMP_FOR_INCREASE, rows=1000, murmur3=self.MURMUR3_PARTITIONER_FOR_INCREASE)
  File "/jenkins/workspace/scylla-4.1/next/scylla-dtest/resharding_test.py", line 162, in _resharding_basic
    actual_data_files_num=data_files_num_during)
  File "/jenkins/workspace/scylla-4.1/next/scylla-dtest/resharding_test.py", line 78, in _verify_number_of_data_files
    (actual_data_files_num, expected_num, reshard_to))
  File "/usr/lib64/python3.7/unittest/case.py", line 1262, in assertLessEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.7/unittest/case.py", line 710, in fail
    raise self.failureException(msg)
AssertionError: 147 not less than or equal to 108 : 147 not less than or equal to 108. Data files amount after resharding should be not more then data files amount before resharding multiplying by 4.
```

The reason is that it counts the sstable files during resharding, where regular compaction
take place so some sstables are counted twice while they are begin compacted.

This likely to have started since scylladb/scylla@7351db7cab7bbf907172940d0bbf8b90afde90ba
`Merge "Reshape upload files and reshard+reshape at boot" from Glauber`
It is more reproducible when running scylla in debug mode that is much slower.

The solution in this patch is to count only the sealed sstables, that have a TOC.txt
component while ignoring unsealed sstables that have a temporary, -TOC.txt.tmp
component.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>