rebuild_test: deflake simple_rebuild_test
As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3471/testReport/junit/rebuild_test/TestRebuild/dtest___simple_rebuild_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/rebuild_test.py", line 104, in simple_rebuild_test
    msg='concurrent rebuild should not be allowed, but one rebuild command should have succeeded.')
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1 : concurrent rebuild should not be allowed, but one rebuild command should have succeeded.
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3471/artifact/logs-gating.release.2/1620035894328_rebuild_test.TestRebuild.simple_rebuild_test/node2.log
```
INFO  2021-05-03 09:57:04,185 [shard 0] storage_service - rebuild from dc: dc1
...
INFO  2021-05-03 09:57:05,058 [shard 0] range_streamer - Rebuild with 127.0.73.1 for keyspace=system_traces succeeded, took 0.04 seconds
INFO  2021-05-03 09:57:05,058 [shard 0] range_streamer - Rebuild succeeded, took 0 seconds, nr_ranges_remaining=0
INFO  2021-05-03 09:57:05,058 [shard 0] storage_service - Streaming for rebuild successful
...
INFO  2021-05-03 09:57:05,097 [shard 0] storage_service - rebuild from dc: dc1
```

Sleeping 0.1 seconds between invocations of the two parallel rebuild
jobs is tight and the may end up serialized on the node and both could
succeed.

This change inserts more keys for non-debug scylla clusters
to make rebuild run for longer (now it takes about 1 second on my local machine)
and adds a couple of debug messages to make the timing clearer in dtest.log.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit d44a7e2b72928ce860fd054747e4f3d6508abf77)