pushed_notifications_test: test_restart_node_localhost: accept also fewer notifications if not wait_and_restart
Following up on e200fca1b4eb49956ee2c5475a2bda1373519089

The test sometimes fails to get the NEW_NODE notification
when invoked with wait_and_restart=False.

E.g. https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1115/testReport/pushed_notifications_test/TestPushedNotifications/test_restart_node_localhost_wait_and_restart_False_/
```
AssertionError: assert 2 >= 3
 +  where 2 = len([{'address': ('127.0.83.2', 9161), 'change_type': 'DOWN'}, {'address': ('127.0.83.2', 9161), 'change_type': 'UP'}])
```

Since the test relies on delicate timing it can't be sure
about this notification so it should support both cases:
getting 2 or 3 notifications.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>