lwt_test: no_cross_shard_ops_test: take into account all 16 queries
As seen in https://jenkins.scylladb.com//view/master/job/scylla-master/job/dtest-release/541//testReport/junit/lwt_test/LwtTest/no_cross_shard_ops_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/lwt_test.py", line 51, in no_cross_shard_ops_test
    assert after[name] - before[name] < 16, "{}:{}".format(before, after)
AssertionError: {'scylla_storage_proxy_replica_cross_shard_ops': 925}:{'scylla_storage_proxy_replica_cross_shard_ops': 941}
```

All 16 queries can be cross shard with the non-shard aware python driver,
so we need to adjust the assertion to be <= 16 rather than < 16.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>