secondary_indexes_test: add excluded errors to ignore_log_patterns before action
When these tests fail on validation, before calling check_errors,
the excluded errors are not processed yet and not added to ignore_log_patterns
causing a secondary test failure that is just distracting.

For exameple:
  FAIL: test_remove_node_during_index_build (secondary_indexes_test.TestSecondaryIndexes)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/local/home/bhalevy/dev/scylla-dtest/secondary_indexes_test.py", line 1036, in test_remove_node_during_index_build
      self._node_action_during_index_build(node_action='remove', nodes=4, rf=3, num_rows=100000)
    File "/local/home/bhalevy/dev/scylla-dtest/secondary_indexes_test.py", line 1098, in _node_action_during_index_build
      num_rows_expected=num_rows, consistency_level=ConsistencyLevel.QUORUM)
    File "/local/home/bhalevy/dev/scylla-dtest/dtest.py", line 1264, in inner
      return func(*args, **kwargs)
    File "/local/home/bhalevy/dev/scylla-dtest/assertions.py", line 132, in assert_row_count_in_select
      num_rows_expected, query, count)
  AssertionError: Expected a row count of 100000 in query "SELECT * FROM b_index_index", but got 99975

Immediately followed by:
  FAIL: test_remove_node_during_index_build (secondary_indexes_test.TestSecondaryIndexes)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/local/home/bhalevy/dev/scylla-dtest/dtest.py", line 945, in tearDown
      self.cleanUpCluster()
    File "/local/home/bhalevy/dev/scylla-dtest/dtest.py", line 980, in cleanUpCluster
      raise AssertionError('Unexpected errors found: {}'.format(found_errors))
  AssertionError: Unexpected errors found: [('node1', ['ERROR 2020-03-11 09:08:18,666 [shard 1] view - Error applying view update to 127.0.82.2: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)'

Add regex=True to calls the check_errors when the expected_errors contain escaped
regular expressions (like "exceptions::unavailable_exception \(Cannot achieve consistency level for cl ONE. Requires 1, alive 0\)")

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>