prepare for `node.stress()` refactor
since in scylladb/scylla-ccm#403 we are changing
`stress()` call to return a nampletuple (and not a regualr tuple)

we need to fix the few places that are doing unpacking

```python
    stdout, stderr = node.stress(...)
ValueError: too many values to unpack (expected 2)
```

also added a helper function that can format any of the two
into printable string to be using in logging

Ref: https://github.com/scylladb/scylla-ccm/pull/403