test_large_partition_with_drop_column: adjust timeout and ck_end for debug mode
This dtest tends to timeout in debug mode.
For example, https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/247/testReport/schema_management_test/TestLargePartitionAlterSchema/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split007___test_large_partition_with_drop_column/
```
self = <schema_management_test.TestLargePartitionAlterSchema object at 0x7f62a0ec4090>

    def test_large_partition_with_drop_column(self):
        session = self.prepare(nodes=1)
        data = self.populate(session=session, data=[], ck_start=0, ck_end=10)

        threads = []
        with ThreadPoolExecutor(max_workers=5) as executor:
            # Insert new rows in background
            threads.append(executor.submit(self.populate, session=session, data=data, ck_start=10, ck_end=1500))
            threads.append(executor.submit(self.read, session=session, ck_max=1500))
            # Wait for running load
            time.sleep(10)
            self.drop_column(session=session, column_name='val1')

            # Memtable flush has to happen after a schema alter concurrently with a read
            logger.debug('Flush data')
            self.cluster.nodelist()[0].flush()

            result = []
>           for future in futures.as_completed(threads, timeout=300):

schema_management_test.py:521:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fs = {<Future at 0x7f62619916d0 state=finished returned NoneType>}
timeout = 300

    def as_completed(fs, timeout=None):
        """An iterator over the given futures that yields each as it completes.

        Args:
            fs: The sequence of Futures (possibly created by different Executors) to
                iterate over.
            timeout: The maximum number of seconds to wait. If None, then there
                is no limit on the wait time.

        Returns:
            An iterator that yields the given Futures as they complete (finished or
            cancelled). If any given Futures are duplicated, they will be returned
            once.

        Raises:
            TimeoutError: If the entire result iterator could not be generated
                before the given timeout.
        """
        if timeout is not None:
            end_time = timeout + time.monotonic()

        fs = set(fs)
        total_futures = len(fs)
        with _AcquireFutures(fs):
            finished = set(
                    f for f in fs
                    if f._state in [CANCELLED_AND_NOTIFIED, FINISHED])
            pending = fs - finished
            waiter = _create_and_install_waiters(fs, _AS_COMPLETED)
        finished = list(finished)
        try:
            yield from _yield_finished_futures(finished, waiter,
                                               ref_collect=(fs,))

            while pending:
                if timeout is None:
                    wait_timeout = None
                else:
                    wait_timeout = end_time - time.monotonic()
                    if wait_timeout < 0:
>                       raise TimeoutError(
                                '%d (of %d) futures unfinished' % (
                                len(pending), total_futures))
E                               TimeoutError: 1 (of 2) futures unfinished
```

Reduce the number of clustering keys and increase the timeout
to deflake the test.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>