test_major_compaction_processes_tables_in_order_by_size: sort_compaction_history: sort by compaction_time, size
As seen in https://jenkins.scylladb.com/job/scylla-5.0/job/dtest-release/84/testReport/compaction_additional_test/TestCompactionAdditional/test_major_compaction_processes_tables_in_order_by_size_10_000_100_000_100_/
```
AssertionError: The list of rows sorted by size is not identical to the list of rows sorted by compaction time
assert [TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_1', size=10000, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 42, 914000)),\n TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_3', size=100, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 42, 914000)),\n TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_2', size=100000, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 43, 28000))] == [TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_3', size=100, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 42, 914000)),\n TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_1', size=10000, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 42, 914000)),\n TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_2', size=100000, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 43, 28000))]
  At index 0 diff: TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_1', size=10000, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 42, 914000)) != TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_3', size=100, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 42, 914000))
  Full diff:
    [
  +  TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_1', size=10000, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 42, 914000)),
     TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_3', size=100, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 42, 914000)),
  -  TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_1', size=10000, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 42, 914000)),
     TestCompactionAdditional.test_major_compaction_processes_tables_in_order_by_size.<locals>.CfSizeTime(name='cf_2', size=100000, compaction_time=datetime.datetime(2023, 3, 20, 12, 26, 43, 28000)),
    ]
 ```

Sorting by compaction_time is insufficient as it may not be unique.
Therefore sort by compaction_time as major key and size as minor key.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>