thrift_tests: test_describe_keyspace: adjust keyspaces for scylla 4.6
'system_distributed_everywhere' was added to the system keyspaces.

Also, assert that all keyspace namess are unique.

Failure seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/795/testReport/thrift_tests/TestMutations/test_describe_keyspace/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/thrift_tests.py", line 1663, in test_describe_keyspace
    assert len(kspaces) == 7, [x.name for x in kspaces]
AssertionError: ['system', 'system_traces', 'Keyspace2', 'system_distributed_everywhere', 'system_distributed', 'system_auth', 'Keyspace1', 'system_schema']
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit 4991d876f4561b7e746e0e1b48f803b4e8c8ade1)