Adjust for cartesian product limit
Due to scylladb/scylla#4751, Scylla now limits the number of restrictions in a query.
Some tests now break due to passing this limit; this patch adjusts the test not to
trigger the check.

Includes patch from Benny fixing

ERROR: large_clustering_in_test (cql_additional_tests.TestCQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla-dtest/cql_additional_tests.py", line 2946, in large_clustering_in_test
    rows = list(session.execute(select_statement, [0, in_values]))
  File "cassandra/cluster.py", line 2141, in cassandra.cluster.Session.execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "cassandra/cluster.py", line 4033, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
ServerError: <Error from server: code=0000 [Server error] message="clustering key cartesian product size 10000 is greater than maximum 100">

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>