compaction,repair additional tests: omit logger module from off-strategy log pattern
scylladb/scylla@fce9d869b4711f7a997556014c8883a81a9023eb
moved the `compact_sstables` function from table to
compaction_manager, changing the log message's log module
along the way.

To fix the affected dtests, just omit the module part of
the log since it doesn't really matter to the test.

Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/1122/testReport/junit/repair_additional_test/TestRepairAdditional/test_repair_triggering_off_strategy_compaction/
```
ccmlib.node.TimeoutError: 27 Mar 2022 12:49:00 [node2] Missing: ['table - Starting off-strategy compaction for ks.cf1', 'table - Done with off-strategy compaction for ks.cf1']:
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>