test_replace_node_same_ip_take_write: do not wait_other_notice when restarting the replacing node
https://github.com/scylladb/scylla-ccm/pull/523 changes
wait_other_notice to wait for other nodes to see the starting node
as normal token owner.  However this test scans the log of the
replacing node, checking its metrics as soon as it reaches `Bootstrap
completed` and waiting for others to notice this node as normal
token owner is too late, causing the following failure:
```
FAILED replace_address_test.py::TestReplaceAddress::test_replace_node_same_ip_take_write[use_host_id-rbo_disabled] - assert (653 - 443) > 250.0
```

Pass `wait_other_notice=False` to `node5.start` to allow only `watch_log_for`
to time the test instead.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit 6f14e03ca286ba28a42edd2b3d5076616ef48afb)